services:
  nextgenchat:
    build:
      context: ./fe
      dockerfile: chatapp.Dockerfile
    container_name: nextgen-chatapp

    #depends_on:
    #  - backend
    ports:
      - "3000:3000"
    env_file:
      - ./fe/.env.local  # Ensure this file exists
    volumes:
      - ./fe/uploads:/app/uploads  # ✅ Mount entire uploads folder
      - ./fe/public/uploads:/app/public/uploads # ✅ Keep this for compatibility
      - ./fe/public/:/app/public/ # ✅ Keep this for compatibility


#  backend:
#    build:
#      context: ./be
#      dockerfile: backend.Dockerfile
#    container_name: chat-backend
#    ports:
#      - "5000:5000"
#    env_file:
#      - ./be/.env

#  n8n:
#    image: n8nio/n8n
#    container_name: n8n
#    restart: always
#    ports:
#      - "5678:5678"
#    environment:
#      - N8N_BASIC_AUTH_ACTIVE=true
#      - N8N_BASIC_AUTH_USER=admin
#      - N8N_BASIC_AUTH_PASSWORD=admin
#      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
#      - DB_TYPE=postgresdb
#      - DB_POSTGRESDB_HOST=${POSTGRES_HOST}
#      - DB_POSTGRESDB_PORT=${POSTGRES_PORT}
#      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
#      - DB_POSTGRESDB_USER=${POSTGRES_USER}
#      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
#    volumes:
#      - ./n8n/data:/home/node/.n8n
#      - ./n8n/local-files:/files  # Mount a directory inside the n8n folder
#    depends_on:
#      - postgres

#  postgres:
#    image: postgres:16
#    container_name: chat-db
#    environment:
#      - POSTGRES_DB
#      - POSTGRES_USER
#      - POSTGRES_PASSWORD
#    volumes:
#      - ./db/data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"

#volumes:
#  n8n_data: